### ISSUE TITLE
请问您本科是哪的？

### ISSUE THREAD

**Issue by 30pig** [mobaitech/Java_Function_Draw#1]

**Comment by mobaitech** [comment]
某不知名双一流

**Comment by 30pig** [comment]
学长好（应该是学长吧），我也是湘大的，看到您源码压缩包里java大作业的文件了，我也选的是画函数工具，本来窃喜以为能够直接抄袭，现在要自己写了，感谢您的作品给我的启发，非常优秀！！！

**Comment by mobaitech** [comment]
大二JAVA的课设吧，难度没多大，我这个算是JAVA新手的项目来着，现在大三了准备考研了，你可以稍微写的更复杂更完善和体系化点，然后pr到我的仓库里面让我瞧瞧

**Comment by 30pig** [comment]
ok到时候班门弄斧一下，学长你也算我这个项目的半个恩师，java课纯是水过来的

**Comment by mobaitech** [comment]
重构了一下仓库，删了没用的文件，把README.md也重构了下，现在流程很清晰，希望能帮到你
